function b_constraints = Constraints(Scenario,...
                                     Control_Horizon,...
                                     Num_Of_Input, ...
                                     Limit_Max, Limit_Min, ...
                                     LThrusterForceX, RThrusterForceX)
switch Scenario
    
    case 1
    
    Thruster_Forces = [];
    for i = 1:1:Control_Horizon
        Thruster_Forces = [Thruster_Forces; ...
                           LThrusterForceX; ...
                           RThrusterForceX];
    end
    
    Thruster_Forces = [Thruster_Forces; -1*Thruster_Forces];
    
    b_constraints = [Limit_Max*ones(Control_Horizon*Num_Of_Input,1);...
                     -1*Limit_Min*ones(Control_Horizon*Num_Of_Input,1)] - ...
                     Thruster_Forces;
end
                                                      

end