function [filtered_yaw, filtered_surge] = LowPassFilter_For_References( ...
                                          filtered_yaw_previous, ...
                                          desired_yaw, ...
                                          yaw_filter_coefficient, ...
                                          filtered_surge_previous, ...
                                          desired_surge,...
                                          surge_filter_coefficient )
                                         
                                  
filtered_yaw = filtered_yaw_previous * yaw_filter_coefficient + ...
    ( 1 - yaw_filter_coefficient ) * desired_yaw;


filtered_surge = filtered_surge_previous * surge_filter_coefficient + ...
    ( 1 - surge_filter_coefficient ) * desired_surge;
                                      
end